### ISSUE TITLE
Bash history security

### ISSUE THREAD

**Issue by jherrlin** [Kodkollektivet/packt-freebie#1]
By executing `java -jar packt-freebie-0.1.0-standalone.jar [email] [pass]` the email and password will be saved in bash history.
Could there be a config file with `email` and `pass` instead?

**Comment by pd222dj** [comment]
Excellent idea. I'll take a look at it.

**Comment by pd222dj** [comment]
This issue has been resolved, see changelog and readme. :)

**Comment by jherrlin** [comment]
@pd222dj would you like to provide the link to the commit where you resolved the issue? :)

**Comment by pd222dj** [comment]
https://github.com/Kodkollektivet/packt-freebie/commit/a2c84a1478b241b6afdd96cc9170536375909914
